adopted: true
fromversion: 5.0.0
id: SOC Identity Containment_V3
version: -1
contentitemexportablefields:
  contentitemfields:
    packID: soc-framework-nist-ir
    packName: SOC Framework NIST IR (800-61)
    itemVersion: 1.6.8
    fromServerVersion: 5.0.0
    toServerVersion: ""
    definitionid: ""
    prevname: ""
    isoverridable: false
    supportedModules: []
aclrelations: []
aclowner:
  id: ""
  type: ""
  name: ""
name: SOC Identity Containment_V3
description: "This playbook handles the main containment actions available with Cortex
  XSIAM, including the following sub-playbooks:  \n* Containment Plan - Isolate endpoint\n
  * Containment Plan - Disable account\n* Containment Plan - Quarantine file\n* Containment
  Plan - Block indicators\n* Containment Plan - Clear user session (currently, the
  playbook supports only Okta)\n\nNote: The playbook inputs enable manipulating the
  execution flow. Read the input descriptions for details."
tags:
- SOC
- SOC_Framework_Unified
- Containment
- Identity
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 8b859cdc-d653-40d8-88b5-856b497221a5
    type: start
    task:
      id: 8b859cdc-d653-40d8-88b5-856b497221a5
      version: -1
      name: ""
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "138"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 285,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "49":
    id: "49"
    taskid: c1bd31ee-eb02-4d8c-87e1-ccdd6b893660
    type: title
    task:
      id: c1bd31ee-eb02-4d8c-87e1-ccdd6b893660
      version: -1
      name: Disable Account
      type: title
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "164"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "58":
    id: "58"
    taskid: 9ab00fc9-7241-4b38-83b8-d1bf0c1bf328
    type: title
    task:
      id: 9ab00fc9-7241-4b38-83b8-d1bf0c1bf328
      version: -1
      name: Clear User Sessions
      type: title
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "166"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 622.5,
          "y": 760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "138":
    id: "138"
    taskid: cb628d2d-29f6-4d2b-8250-f7d20b163239
    type: condition
    task:
      id: cb628d2d-29f6-4d2b-8250-f7d20b163239
      version: -1
      name: Should containment automatically?
      description: |+
        Whether to perform containment actions automatically or manually.

      type: condition
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#default#':
      - "139"
      "yes":
      - "147"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.AutoContainment
            iscontext: true
          right:
            value:
              simple: "True"
          ignorecase: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 285,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "139":
    id: "139"
    taskid: 1e2a11f2-86d5-4949-b4a2-647966d5366c
    type: collection
    task:
      id: 1e2a11f2-86d5-4949-b4a2-647966d5366c
      version: -1
      name: Which containment actions would you like to perform?
      description: Select which indicators to block.
      type: collection
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "147"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 172.5,
          "y": 405
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to: null
      subject: null
      body: null
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: Select Users to disable
        required: false
        gridcolumns: []
        defaultrows: []
        type: multiSelect
        options: []
        optionsarg:
        - complex:
            root: inputs.Username
            transformers:
            - operator: uniq
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      - id: "1"
        label: ""
        labelarg:
          simple: Select Users to clear their sessions
        required: false
        gridcolumns: []
        defaultrows: []
        type: multiSelect
        options: []
        optionsarg:
        - complex:
            root: inputs.Username
            transformers:
            - operator: uniq
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: Which containment actions would you like to perform?
      description: Select which containment actions to perform
      sender: ""
      expired: false
      totalanswers: 0
      syncid: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "147":
    id: "147"
    taskid: f486236e-11d4-4d91-8f9d-252577239705
    type: title
    task:
      id: f486236e-11d4-4d91-8f9d-252577239705
      version: -1
      name: Containment
      type: title
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "49"
      - "58"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 285,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "148":
    id: "148"
    taskid: 48ad472b-5301-4524-899a-41e29d38151d
    type: title
    task:
      id: 48ad472b-5301-4524-899a-41e29d38151d
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1485
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "157":
    id: "157"
    taskid: 27724d31-2a6c-4301-8d4a-53cbe0a9e2af
    type: condition
    task:
      id: 27724d31-2a6c-4301-8d4a-53cbe0a9e2af
      version: -1
      name: Disable Account?
      type: condition
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      "No":
      - "148"
      "Yes":
      - "169"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1115
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to: null
      subject: null
      body:
        simple: Would you like to Disable the account
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
      replyOptions:
      - "Yes"
      - "No"
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "159":
    id: "159"
    taskid: d483fe6a-0a36-450f-8467-9de7bdf3c71e
    type: condition
    task:
      id: d483fe6a-0a36-450f-8467-9de7bdf3c71e
      version: -1
      name: Clear User Sessions?
      type: condition
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      "No":
      - "148"
      "Yes":
      - "170"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 735,
          "y": 1115
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to: null
      subject: null
      body:
        simple: Would you like to clear the users sessions?
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
      replyOptions:
      - "Yes"
      - "No"
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "164":
    id: "164"
    taskid: 6e17162a-b3bf-4324-861b-a3fee0bf791c
    type: condition
    task:
      id: 6e17162a-b3bf-4324-861b-a3fee0bf791c
      version: -1
      name: Miter Technique for user account disablement
      description: |-
        Techniques Covered
        T1078 – Valid Accounts
        T1110 – Brute Force
        T1136 – Create Account
        T1098 – Account Manipulation
        T1556 – Modify Authentication Process
        T1021 – Remote Services
        T1041 – Exfiltration Over C2 Channel
        T1070.001 – Clear Windows Event Logs
        T1486 – Data Encrypted for Impact
        T1087 – Account Discovery
        T1496 – Resource Hijacking
      type: condition
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#default#':
      - "148"
      "yes":
      - "157"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: match
          left:
            value:
              simple: SOCFramework.Mitre.Technique.ID
            iscontext: true
          right:
            value:
              simple: (T1078|T1110|T1136|T1098|T1556|T1021|T1041|T1070\.001|T1486|T1087|T1496)
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 930
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "166":
    id: "166"
    taskid: c7bcb661-d702-44b3-8f74-0192cfe976d5
    type: condition
    task:
      id: c7bcb661-d702-44b3-8f74-0192cfe976d5
      version: -1
      name: Miter Technique for clearing user session
      description: |-
        Techniques Covered
        T1078 – Valid Accounts
        T1110 – Brute Force
        T1136 – Create Account
        T1098 – Account Manipulation
        T1556 – Modify Authentication Process
        T1021 – Remote Services
        T1041 – Exfiltration Over C2 Channel
        T1070.001 – Clear Windows Event Logs
        T1486 – Data Encrypted for Impact
        T1087 – Account Discovery
        T1496 – Resource Hijacking
      type: condition
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#default#':
      - "148"
      "yes":
      - "159"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: match
          left:
            value:
              simple: SOCFramework.Mitre.Technique.ID
            iscontext: true
          right:
            value:
              simple: (T1078|T1110|T1136|T1098|T1556|T1021|T1041|T1070\.001|T1486|T1087|T1496)
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 622.5,
          "y": 930
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "169":
    id: "169"
    taskid: 3620d907-fa34-4389-bc3f-d3845180a731
    type: regular
    task:
      id: 3620d907-fa34-4389-bc3f-d3845180a731
      version: -1
      name: Disable Account — Universal Command
      description: 'Universal Command: soc-disable-user'
      script: SOCCommandWrapper
      type: regular
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "148"
    scriptarguments:
      Action_Actor:
        simple: automation
      LifeCycle:
        simple: NIST_IR
      Phase:
        simple: Containment
      action:
        simple: soc-disable-user
      list_name:
        simple: SOCFrameworkActions_V3
      output_key:
        simple: Containment.Execution
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "170":
    id: "170"
    taskid: c8713aed-dd60-47a2-aed9-b18d25f17d5e
    type: regular
    task:
      id: c8713aed-dd60-47a2-aed9-b18d25f17d5e
      version: -1
      name: Clear User Sessions — Universal Command
      description: 'Universal Command: soc-clear-sessions'
      script: SOCCommandWrapper
      type: regular
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "148"
    scriptarguments:
      Action_Actor:
        simple: automation
      LifeCycle:
        simple: NIST_IR
      Phase:
        simple: Containment
      action:
        simple: soc-clear-sessions
      list_name:
        simple: SOCFrameworkActions_V3
      output_key:
        simple: Containment.Execution
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 847.5,
          "y": 1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
outlinetasks: {}
system: true
view: |-
  {
    "linkLabelsPosition": {
      "138_139_#default#": 0.64
    },
    "paper": {
      "dimensions": {
        "height": 1495,
        "width": 1177.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: AutoContainment
  value:
    simple: "False"
  required: false
  description: |-
    Whether to execute containment plan (except isolation) automatically.
    The specific containment playbook inputs should also be set to 'True'.
  playbookInputQuery: null
- key: UserContainment
  value:
    simple: "True"
  required: false
  description: Set to 'True' to disable the user account.
  playbookInputQuery: null
- key: ClearUserSessions
  value:
    simple: "True"
  required: false
  description: Set to 'True' to clear the user active Okta sessions.
  playbookInputQuery: null
- key: Username
  value:
    simple: ${SOCFramework.Artifacts.UserName}
  required: false
  description: The username to disable.
  playbookInputQuery: null
- key: IAMUserDomain
  value:
    simple: ${SOCFramework.Artifacts.Domain}
  required: false
  description: The Okta IAM users domain. The domain will be appended to the username.
    e.g. username@IAMUserDomain.
  playbookInputQuery: null
- key: FeaturedUser
  value:
    simple: "False"
  required: false
  description: Is this a Featured User?
  playbookInputQuery: null
- key: FeaturedAD
  value:
    simple: "False"
  required: false
  description: Is this a Featured Active Directory Group?
  playbookInputQuery: null
outputs:
- contextPath: Blocklist.Final
  description: The blocked accounts.
  type: unknown
- contextPath: QuarantinedFilesFromEndpoints
  description: The quarantined files from endpoint.
  type: unknown
- contextPath: Core.blocklist.added_hashes
  description: The file Hash that was added to the blocklist.
- contextPath: Core.Isolation.endpoint_id
  description: The isolated endpoint ID.
possibleresponses: []
